name: beauty_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter

  share_plus: ^4.0.4

  cached_network_image: ^3.2.0
  card_swiper: ^2.0.3
  flutter_pagewise: ^2.0.1
  flutter_svg: ^1.0.3
  flex_color_scheme: ^5.0.1

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
