name: beauty_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_native_splash: ^2.2.11
  get_storage: ^2.0.3
  smooth_page_indicator: ^1.0.0+2
  styled_widget: ^0.4.0+3

  # image & themes
  cached_network_image: ^3.2.0
  flutter_svg: ^1.0.3
  flex_color_scheme: ^6.0.1

  # utility
  card_swiper: ^2.0.3
  flutter_pagewise: ^2.0.4
  flutter_secure_storage: ^5.0.2
  pinput: ^2.2.16
  # share_plus: ^4.0.4
  timeago: ^3.2.2

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
